name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test Container Image
    runs-on: ubuntu-latest

    # Run a local registry to push to
    services:
      registry:
        image: registry:2
        ports:
          - 5001:5000

    env:
      TEST_TAG: localhost:5001/qbaware/render-redeploy-action:latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Docker BuildX
        id: setup-buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: network=host

      - name: Build the Container
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.TEST_TAG }}

      - name: Run the Container
        id: run
        env:
          RENDER_API_KEY: 123456789
          RENDER_SERVICE_ID: 123456789
        run: |
          docker run \
            --env RENDER_API_KEY="${{ env.RENDER_API_KEY }}" \
            --env RENDER_SERVICE_ID="${{ env.RENDER_SERVICE_ID }}" \
            --rm ${{ env.TEST_TAG }} || true
